turf/ASaviorWarpers
	warp
		layer=500
		density=0
		var/goingto
		Entered(mob/M)
			if(!ismob(M)) return
			if(M.teleporting) return
			M.teleporting = 1
			M.density = 0
			M.Move(locate(goingto))
			M.teleporting = 0
			M.density = 1
		Exited()
			usr.layer=initial(usr.layer)
		Konoha
			Kage
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Kage/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Kage/A
			TowerA
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerA/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerA/A

				A1
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerA/B1
				B1
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerA/A1
			TowerB
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerB/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerB/A

				A1
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerB/B1
				B1
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerB/A1

			TowerC
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerC/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerC/A

				A1
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerC/B1
				B1
					goingto=/turf/ASaviorWarpers/warp/Konoha/TowerC/A1

			Acad
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Acad/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Acad/A

			House1
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House1/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House1/A

			House2
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House2/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House2/A

			House3
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House3/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House3/A
			House4
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House4/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House4/A
			House5
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House5/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House5/A
			House6
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House6/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House6/A
			House7
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House7/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House7/A
			House8
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House8/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House8/A
			House9
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House9/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House9/A
			House10
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House10/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House10/A
			House11
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House11/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House11/A
			House12
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/House12/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/House12/A
			Shop1
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Shop1/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Shop1/A
			Shop2
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Shop2/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Shop2/A
			Police
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Police/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Police/A

				A1
					goingto=/turf/ASaviorWarpers/warp/Konoha/Police/B1
				B1
					goingto=/turf/ASaviorWarpers/warp/Konoha/Police/A1
			RestA
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/RestA/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/RestA/A
			RestB
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/RestB/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/RestB/A
			Rand1
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand1/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand1/A
			Rand2
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand2/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand2/A
			Rand3
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand3/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand3/A
			Rand4
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand4/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand4/A
			Rand5
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand5/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand5/A
			Rand6
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand6/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand6/A
			Rand7
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand7/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Rand7/A
			Cult1
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Cult1/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Cult1/A
			Cult2
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Cult2/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Cult2/A
			Cult3
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Cult3/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Cult3/A
			Clan1
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Clan1/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Clan1/A
			Clan2
				A
					goingto=/turf/ASaviorWarpers/warp/Konoha/Clan2/B
				B
					goingto=/turf/ASaviorWarpers/warp/Konoha/Clan2/A
